version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ./db_script/mysql:/docker-entrypoint-initdb.d
#      - read_only: true
#        source: ./db_script/mysql
#        target: /docker-entrypoint-initdb.d
#        type: volume